name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Build docs
        run: npm run build:ghpages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          rm -rf docs/*
          cp -r dist-ghpages/* docs/
          git add docs
          git commit -m "Deploy add-in" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${DEPLOY_PAT}@github.com/Neverneverbabe/exceljax.git
          git push origin HEAD:main
